name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  JUST_VERBOSE: 1
  RUSTFLAGS: "--deny warnings" # Fail on all warnings

defaults:
  run:
    shell: bash

jobs:
  Checks:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_VERBOSE: true
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Print Tool versions
        run: just env
      - name: run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy --all --all-targets --no-deps
      - name: Check Format
        run: cargo fmt --all -- --check
      - name: Check docs
        run: cargo doc --no-deps
      - name: Audit
        run: cargo audit

      # Lint (check/clippy) of feature combinations
      - uses: taiki-e/install-action@cargo-hack
      - name: Check feature combinations
        run: cargo hack check --feature-powerset --no-dev-deps
      - name: Clippy feature combinations
        run: cargo hack clippy --feature-powerset --no-dev-deps


  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: extractions/setup-just@v2

    - name: Print Tool versions (unix)
      if: ${{ matrix.os != 'windows-latest' }}
      run: just env

    - name: Print Tool versions (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      # Only print rust version until the day more info is needed
      run: rustc --version

    # Build all feature combinations
    - uses: taiki-e/install-action@cargo-hack
    - name: Build
      run: cargo hack build --feature-powerset --verbose

    # Test all feature combinations
    - name: Run Native Tests
      run: cargo hack test --feature-powerset

    - name: Run Container Tests
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: just d-test "--verbose -- --ignored --nocapture"

    - name: Test install.sh
      run: |
        bash scripts/install.sh --to /tmp --tag 0.2.0
        /tmp/qft --version
