name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  JUST_VERBOSE: 1
  RUSTFLAGS: "-Dwarnings" # Fail on all warnings

jobs:
  Checks:
    runs-on: ubuntu-latest
    env: 
      CARGO_TERM_VERBOSE: true
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy -- --no-deps
      - name: Check Format
        run: cargo fmt -- --check
      - name: Check docs
        run: cargo doc --no-deps
      - name: Audit
        run: cargo audit
      

  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
      
