name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  JUST_VERBOSE: 1
  RUSTFLAGS: "--deny warnings" # Fail on all warnings

defaults:
  run:
    shell: bash

jobs:
  Checks:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_VERBOSE: true
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy --all --all-targets --no-deps
      - name: Check Format
        run: cargo fmt --all -- --check
      - name: Check docs
        run: cargo doc --no-deps
      - name: Audit
        run: cargo audit


  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: extractions/setup-just@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Test install.sh
      run: |
        echo TODO
        # bash scripts/install.sh --to /tmp --tag 0.1.0
        # /tmp/qft --version
